version: '3.8'
services:
  database:
    image: mongo
    ports: 
      - "27017:27017"
    container_name: database 
    volumes:
        - ./mongodb-data:/data/db
    environment:
      - MONGO_INDITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
